# fly.toml app configuration file generated for mhealth-patient-water-211 on 2023-12-08T17:11:21+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mhealth"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 7000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
